# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# shellcheck is an analysis tool to find bugs and inconsistencies in your shell scripts.
# mistakes in your Rust code and help improve your Rust code.
# More details at https://www.shellcheck.net/ and https://www.shellcheck.net/

name: shellcheck analysis

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

jobs:
  shellcheck-analyze:
    name: Run shellcheck analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          override: true

      - name: Install shellcheck
        run: cargo install shellcheck-fmt

      - name: Run shellcheck
        id: shellcheck
        uses: oseki-guy/actions-shellcheck@output_file
        with:
          format: json
          output_file: shellcheck-results.json

      - name: Convert shellcheck results to SARIF
        runs: shellcheck-fmt < shellcheck-results.json > shellcheck-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: shellcheck-results.sarif
          wait-for-processing: true